version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: cantillo
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: prisma_db
    ports:
      - "5433:5432"
    volumes:
      - ./data-apiusuarios:/var/lib/postgresql/data